# Generated by Django 3.2.6 on 2021-08-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Computer', 'Computer'), ('Electrical', 'Electrical'), ('Marine', 'Marine'), ('Mechanical', 'Mechanical'), ('Common', 'Common'), ('Civil', 'Civil')], max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('t', models.IntegerField(blank=True, null=True)),
                ('p', models.IntegerField(blank=True, null=True)),
                ('c', models.IntegerField(blank=True, null=True)),
                ('t_cont_assess', models.IntegerField(blank=True, null=True)),
                ('t_final', models.IntegerField(blank=True, null=True)),
                ('p_cont_asses', models.IntegerField(blank=True, null=True)),
                ('p_final', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
