# Generated by Django 3.2.6 on 2021-08-23 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
        ('Subject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.CreateModel(
            name='AssignedSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subject.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teacher.teacher')),
            ],
        ),
    ]
