# Generated by Django 3.2.6 on 2021-08-23 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_auto_20210823_1105'),
        ('Teacher', '0006_auto_20210823_1105'),
        ('Subject', '0004_alter_assignedsubject_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teacher.teacher'),
        ),
        migrations.DeleteModel(
            name='AssignedSubject',
        ),
    ]
