# Generated by Django 3.2.6 on 2021-08-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subject', '0005_auto_20210823_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['semester', 'department', 'code']},
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(blank=True, choices=[('Mechanical', 'Mechanical'), ('Combined', 'Combined'), ('Marine', 'Marine'), ('Civil', 'Civil'), ('Computer', 'Computer'), ('Electrical', 'Electrical')], default='Combined', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(blank=True, choices=[('5th', '5th'), ('7th', '7th'), ('4th', '4th'), ('2nd', '2nd'), ('1st', '1st'), ('6th', '6th'), ('8th', '8th'), ('3rd', '3rd')], default='1st', max_length=3, null=True),
        ),
    ]
