# Generated by Django 3.2.6 on 2021-08-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subject', '0007_auto_20210823_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedsubject',
            name='shift',
            field=models.CharField(choices=[('Evening', 'Evening'), ('Day', 'Day')], default='Day', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(blank=True, choices=[('8th', '8th'), ('5th', '5th'), ('1st', '1st'), ('7th', '7th'), ('6th', '6th'), ('3rd', '3rd'), ('2nd', '2nd'), ('4th', '4th')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='technology',
            field=models.CharField(blank=True, choices=[('Civil', 'Civil'), ('Electrical', 'Electrical'), ('Computer', 'Computer'), ('Combined', 'Combined'), ('Marine', 'Marine'), ('Mechanical', 'Mechanical')], default='Combined', max_length=15, null=True),
        ),
    ]
