# Generated by Django 3.2.6 on 2021-08-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_alter_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('Marine', 'Marine'), ('Civil', 'Civil'), ('Computer', 'Computer'), ('Combined', 'Combined'), ('Mechanical', 'Mechanical'), ('Electrical', 'Electrical')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(blank=True, choices=[('Instructor', 'Instructor'), ('Jr. Instructor', 'Jr. Instructor')], default='Jr. Instructor', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11, null=True),
        ),
    ]
