# Generated by Django 3.2.6 on 2021-08-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_auto_20210823_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['department', 'name']},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('Electrical', 'Electrical'), ('Computer', 'Computer'), ('Mechanical', 'Mechanical'), ('Combined', 'Combined'), ('Marine', 'Marine'), ('Civil', 'Civil')], max_length=10, null=True),
        ),
    ]
