# Generated by Django 3.2.6 on 2021-08-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0005_auto_20210823_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('Combined', 'Combined'), ('Civil', 'Civil'), ('Computer', 'Computer'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Marine', 'Marine')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(blank=True, choices=[('Instructor', 'Instructor'), ('Jr. Instructor', 'Jr. Instructor')], default='Jr. Instructor', max_length=20, null=True),
        ),
    ]
