# Generated by Django 3.2.6 on 2021-08-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0007_auto_20210823_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['technology', 'name']},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.AddField(
            model_name='teacher',
            name='technology',
            field=models.CharField(blank=True, choices=[('Mechanical', 'Mechanical'), ('Combined', 'Combined'), ('Marine', 'Marine'), ('Computer', 'Computer'), ('Civil', 'Civil'), ('Electrical', 'Electrical')], max_length=10, null=True),
        ),
    ]
