# Generated by Django 3.2.6 on 2021-08-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(verbose_name='Start Time')),
                ('duration', models.IntegerField(verbose_name='Duration (Minutes)')),
            ],
        ),
    ]
