# Generated by Django 3.2.6 on 2021-08-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Period', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
