# Generated by Django 3.2.6 on 2021-08-23 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Period', '0002_period_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['num']},
        ),
    ]
