# Generated by Django 3.2.6 on 2021-08-23 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
        ('Subject', '0002_auto_20210823_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subject.assignedsubject'),
        ),
    ]
