# Generated by Django 3.2.6 on 2021-08-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20210823_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='department',
            field=models.CharField(choices=[('Marine', 'Marine'), ('Civil', 'Civil'), ('Computer', 'Computer'), ('Combined', 'Combined'), ('Mechanical', 'Mechanical'), ('Electrical', 'Electrical')], max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(choices=[('6th', '6th'), ('1st', '1st'), ('3rd', '3rd'), ('8th', '8th'), ('7th', '7th'), ('2nd', '2nd'), ('5th', '5th'), ('4th', '4th')], max_length=3),
        ),
    ]
