# Generated by Django 3.2.6 on 2021-08-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20210823_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['semester', 'department', 'period', 'sub']},
        ),
        migrations.AddField(
            model_name='class',
            name='day',
            field=models.CharField(choices=[('Fri', 'Fri'), ('Sun', 'Sun'), ('Sat', 'Sat'), ('Tue', 'Tue'), ('Mon', 'Mon'), ('Wed', 'Wed'), ('Thu', 'Thu')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='class',
            name='department',
            field=models.CharField(choices=[('Electrical', 'Electrical'), ('Computer', 'Computer'), ('Mechanical', 'Mechanical'), ('Combined', 'Combined'), ('Marine', 'Marine'), ('Civil', 'Civil')], max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(choices=[('2nd', '2nd'), ('7th', '7th'), ('6th', '6th'), ('5th', '5th'), ('3rd', '3rd'), ('1st', '1st'), ('4th', '4th'), ('8th', '8th')], max_length=3),
        ),
    ]
