# Generated by Django 3.2.6 on 2021-08-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20210823_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='day',
            field=models.CharField(choices=[('Mon', 'Mon'), ('Sat', 'Sat'), ('Thu', 'Thu'), ('Sun', 'Sun'), ('Fri', 'Fri'), ('Tue', 'Tue'), ('Wed', 'Wed')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='class',
            name='department',
            field=models.CharField(choices=[('Marine', 'Marine'), ('Computer', 'Computer'), ('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Civil', 'Civil'), ('Combined', 'Combined')], max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(choices=[('2nd', '2nd'), ('3rd', '3rd'), ('8th', '8th'), ('1st', '1st'), ('7th', '7th'), ('6th', '6th'), ('5th', '5th'), ('4th', '4th')], max_length=3),
        ),
    ]
