# Generated by Django 3.2.6 on 2021-08-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subject', '0007_auto_20210823_1348'),
        ('Core', '0008_auto_20210823_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['period', 'sub'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.RemoveField(
            model_name='class',
            name='shift',
        ),
        migrations.AlterField(
            model_name='class',
            name='day',
            field=models.CharField(choices=[('Sun', 'Sun'), ('Mon', 'Mon'), ('Fri', 'Fri'), ('Tue', 'Tue'), ('Sat', 'Sat'), ('Wed', 'Wed'), ('Thu', 'Thu')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='class',
            name='period_count',
            field=models.CharField(choices=[('Double', 'Double'), ('Single', 'Single')], default='Single', max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subject.assignedsubject'),
        ),
    ]
